version: "3.5"

services:
  app:
    build: ./
    container_name: "health_eye_api"
    restart: unless-stopped
    volumes:
      - ./health_eye_api.ini:/etc/supervisor.d/health_eye_api.ini
      - ./instance/config.py:/app/instance/config.py
    environment:
      - TZ=Asia/Shanghai
  nginx:
    image: nginx
    ports:
      - 8090:8090
    container_name: "health_eye_nginx"
    restart: unless-stopped
    links:
     - app:health_eye_api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./health_eye_api.conf:/etc/nginx/conf.d/health_eye_api.conf
    environment:
      - TZ=Asia/Shanghai
volumes:
  dist:
